kind: Component
apiVersion: backstage.io/v1alpha1
metadata:
  name: s1
  annotations:
    harness.io/project-url: https://laxmiharness.pr2.harness.io/ng/account/6cBjZs_fTWCiRITqFyRrgQ/home/orgs/default/projects/Test/details
    harness.io/cd-serviceId: s1
    harness.io/services: |
      s1: https://laxmiharness.pr2.harness.io/ng/account/6cBjZs_fTWCiRITqFyRrgQ/cd/orgs/default/projects/Test/services/s1
  title: s1
  tags: []
spec:
  type: Service
  lifecycle: Unknown
  owner: Unknown
  domain: default
  system: Test
